'use client';

import React, { useEffect, useMemo, useRef, useState, useCallback } from 'react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Input } from '@/components/ui/input';
import {
  Undo2, Redo2, Eraser, Pencil, Highlighter, Type, Droplet,
  Image as ImageIcon, Download, Maximize2, Minimize2, Square, Circle,
  Minus, Grid, Trash2, Hand, PaintBucket
} from 'lucide-react';

type Tool =
  | 'pen'
  | 'marker'
  | 'eraser'
  | 'line'
  | 'rect'
  | 'circle'
  | 'text'
  | 'eyedropper'
  | 'pan'
  | 'fill';

interface DrawingCanvasProps {
  className?: string;
  disabled?: boolean;
  onDrawEnd?: (dataUrl: string) => void;
  initialImage?: string | null;
  maxHistory?: number;
  /** إذا تركتها فارغة، اللوحة تتمدّد تلقائياً داخل الحاوية */
  width?: number;
  height?: number;
}

/**
 * Generated by GPT-5 Thinking — Canvas Pro
 * - Backing canvas (hiDPI) + display canvas (camera render)
 * - True pan/zoom viewport (لا يحرّك البكسلات المخزّنة)
 * - Flood fill with tolerance
 */
export function DrawingCanvas({
  className,
  disabled = false,
  onDrawEnd,
  initialImage = null,
  maxHistory = 60,
  width,
  height,
}: DrawingCanvasProps) {
  // DOM
  const containerRef = useRef<HTMLDivElement>(null);
  const displayRef = useRef<HTMLCanvasElement>(null);
  const overlayRef = useRef<HTMLCanvasElement>(null);

  // Backing canvas (offscreen) يخزّن الرسم الحقيقي بدقّة عالية
  const backingRef = useRef<HTMLCanvasElement | null>(null);

  // مقاسات منطقية (CSS pixels)
  const [size, setSize] = useState<{ w: number; h: number }>({
    w: width || 800,
    h: height || 450,
  });

  // DPI
  const [dpr, setDpr] = useState<number>(1);

  // الكاميرا
  const [zoom, setZoom] = useState<number>(1);
  const [pan, setPan] = useState<{ x: number; y: number }>({ x: 0, y: 0 });

  // الحالة
  const [tool, setTool] = useState<Tool>('pen');
  const [color, setColor] = useState<string>('#1f2937'); // slate-800
  const [thickness, setThickness] = useState<number>(5);
  const [opacity, setOpacity] = useState<number>(1);
  const [showGrid, setShowGrid] = useState<boolean>(false);

  // النص
  const [textValue, setTextValue] = useState<string>('');
  const [textSize, setTextSize] = useState<number>(24);

  // الدلو (التعبئة)
  const [fillTolerance, setFillTolerance] = useState<number>(24); // 0..100

  // الرسم الحر
  const isDrawingRef = useRef<boolean>(false);
  const lastPtCssRef = useRef<{ x: number; y: number } | null>(null);

  // التاريخ
  const [history, setHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState<number>(-1);
  const historyIndexRef = useRef<number>(-1);
  useEffect(() => { historyIndexRef.current = historyIndex; }, [historyIndex]);

  // شبكة الخلفية CSS
  const gridBg = useMemo(() => {
    if (!showGrid) return '';
    const s = 32;
    return `repeating-linear-gradient(0deg, rgba(0,0,0,0.06) 0, rgba(0,0,0,0.06) 1px, transparent 1px, transparent ${s}px),
            repeating-linear-gradient(90deg, rgba(0,0,0,0.06) 0, rgba(0,0,0,0.06) 1px, transparent 1px, transparent ${s}px)`;
  }, [showGrid]);

  // Helpers: كانفس العرض/الواجهة
  const getDisplayCtx = () => displayRef.current!.getContext('2d')!;
  const getOverlayCtx = () => overlayRef.current!.getContext('2d')!;
  const getBackingCtx = () => backingRef.current!.getContext('2d', { willReadFrequently: true }) as CanvasRenderingContext2D;

  // تحويل إحداثيات الشاشة (client) → إحداثيات CSS داخل اللوحة (قبل الكاميرا) → ثم بكسلات فعلية
  const clientToCss = useCallback((clientX: number, clientY: number) => {
    const rect = displayRef.current!.getBoundingClientRect();
    const xCss = (clientX - rect.left - pan.x) / zoom;
    const yCss = (clientY - rect.top - pan.y) / zoom;
    // حصر داخل اللوحة
    return { x: Math.max(0, Math.min(size.w, xCss)), y: Math.max(0, Math.min(size.h, yCss)) };
  }, [pan.x, pan.y, zoom, size.w, size.h]);

  const cssToPx = useCallback((ptCss: { x: number; y: number }) => {
    return { x: Math.round(ptCss.x * dpr), y: Math.round(ptCss.y * dpr) };
  }, [dpr]);

  // رسم محتوى الـ backing إلى العرض مع الكاميرا
  const renderAll = useCallback(() => {
    if (!displayRef.current || !overlayRef.current || !backingRef.current) return;
    const dctx = getDisplayCtx();
    // نشتغل بوحدات CSS: setTransform(dpr) ثم كاميرا
    dctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    dctx.clearRect(0, 0, size.w, size.h);
    dctx.save();
    dctx.translate(pan.x, pan.y);
    dctx.scale(zoom, zoom);
    // ارسم backing (بوحدات CSS عبر drawImage srcPx → dstCss)
    dctx.drawImage(
      backingRef.current,
      0, 0, backingRef.current.width, backingRef.current.height,
      0, 0, size.w, size.h
    );
    dctx.restore();
  }, [dpr, size.w, size.h, pan.x, pan.y, zoom]);

  // تهيئة المقاسات وDPR + إنشاء backing
  const setupCanvases = useCallback((keepContent = true) => {
    if (!displayRef.current || !overlayRef.current) return;

    const devicePixelRatio = Math.max(1, Math.floor(window.devicePixelRatio || 1));
    setDpr(devicePixelRatio);

    const disp = displayRef.current;
    const over = overlayRef.current;

    // تحديث مقاس كانفس العرض/المعاينة (بالبكسلات الفعلية)
    disp.width = Math.floor(size.w * devicePixelRatio);
    disp.height = Math.floor(size.h * devicePixelRatio);
    disp.style.width = `${size.w}px`;
    disp.style.height = `${size.h}px`;

    over.width = disp.width;
    over.height = disp.height;
    over.style.width = `${size.w}px`;
    over.style.height = `${size.h}px`;

    // backing
    const oldBacking = backingRef.current;
    const newBacking = document.createElement('canvas');
    newBacking.width = Math.floor(size.w * devicePixelRatio);
    newBacking.height = Math.floor(size.h * devicePixelRatio);
    backingRef.current = newBacking;

    const nctx = getBackingCtx();
    nctx.clearRect(0, 0, newBacking.width, newBacking.height);

    if (keepContent && oldBacking) {
      // احتفاظ بالمحتوى السابق مع تحجيم/ملاءمة المقاس الجديد
      nctx.drawImage(oldBacking, 0, 0, oldBacking.width, oldBacking.height, 0, 0, newBacking.width, newBacking.height);
    }

    renderAll(); // إعادة العرض
  }, [size.w, size.h, renderAll]);

  // مراقبة الحاوية للتجاوب
  useEffect(() => {
    if (width && height) {
      setSize({ w: width, h: height });
      return;
    }
    const el = containerRef.current;
    if (!el) return;
    const ro = new ResizeObserver(entries => {
      for (const entry of entries) {
        const cr = entry.contentRect;
        const w = Math.max(320, Math.floor(cr.width));
        const h = Math.max(220, Math.floor((cr.width * 9) / 16));
        setSize({ w, h });
      }
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [width, height]);

  // عند تغيّر الحجم أو dpr (عبر setup)
  useEffect(() => {
    setupCanvases(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [size.w, size.h]);

  // History
  const pushHistory = useCallback((customUrl?: string) => {
    const dataUrl = customUrl ?? backingRef.current!.toDataURL('image/png');
    setHistory(prev => {
      const idx = Math.min(Math.max(historyIndexRef.current, -1), prev.length - 1);
      const upto = prev.slice(0, idx + 1);
      const next = [...upto, dataUrl].slice(-maxHistory);
      const newIndex = next.length - 1;
      historyIndexRef.current = newIndex;
      setHistoryIndex(newIndex);
      return next;
    });
    onDrawEnd?.(dataUrl);
  }, [maxHistory, onDrawEnd]);
  
  // تحميل صورة ابتدائية
  useEffect(() => {
    if (!initialImage) {
        pushHistory(backingRef.current!.toDataURL('image/png'));
        return;
    };
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.src = initialImage;
    img.onload = () => {
      const bctx = getBackingCtx();
      // احتواء Contain داخل اللوحة (بوحدات CSS ثم تحويل لبكسلات)
      const scale = Math.min(size.w / img.width, size.h / img.height);
      const wCss = img.width * scale;
      const hCss = img.height * scale;
      const xCss = (size.w - wCss) / 2;
      const yCss = (size.h - hCss) / 2;

      const xPx = Math.round(xCss * dpr);
      const yPx = Math.round(yCss * dpr);
      const wPx = Math.round(wCss * dpr);
      const hPx = Math.round(hCss * dpr);

      bctx.clearRect(0, 0, backingRef.current!.width, backingRef.current!.height);
      bctx.drawImage(img, 0, 0, img.width, img.height, xPx, yPx, wPx, hPx);
      pushHistory();
      renderAll();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialImage, dpr, size.w, size.h]);

  // مسح طبقة المعاينة
  const clearOverlay = useCallback(() => {
    const octx = getOverlayCtx();
    octx.setTransform(dpr, 0, 0, dpr, 0, 0);
    octx.clearRect(0, 0, size.w, size.h);
  }, [dpr, size.w, size.h]);

  // ضبط أسلوب القلم على backing (ببكسلات فعلية)
  const setStrokeStyleBacking = (ctx: CanvasRenderingContext2D, pressure = 0.5) => {
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    const base = thickness;
    const dynCss = Math.max(1, base * (0.3 + (pressure || 0.5) * 0.7));
    const dynPx = dynCss * dpr; // ارسم بالبكسلات الفعلية
    ctx.lineWidth = dynPx;

    ctx.globalAlpha = opacity;
    if (tool === 'marker') ctx.globalAlpha = Math.min(1, opacity * 0.5);
    ctx.globalCompositeOperation = tool === 'eraser' ? 'destination-out' : 'source-over';
    ctx.strokeStyle = tool === 'eraser' ? '#000' : color;
  };

  // رسم مقطع خط على backing (نقاط CSS → نحول لبكسل قبل الرسم)
  const strokeSegmentBacking = (fromCss: { x: number; y: number }, toCss: { x: number; y: number }, pressure = 0.5) => {
    const ctx = getBackingCtx();
    const f = cssToPx(fromCss);
    const t = cssToPx(toCss);
    ctx.save();
    setStrokeStyleBacking(ctx, pressure);
    ctx.beginPath();
    ctx.moveTo(f.x + 0.5, f.y + 0.5);
    ctx.lineTo(t.x + 0.5, t.y + 0.5);
    ctx.stroke();
    ctx.restore();
    renderAll();
  };

  // معاينة أشكال على overlay (بوحدات CSS + كاميرا)
  const drawPreviewShape = (startCss: { x: number; y: number }, currentCss: { x: number; y: number }) => {
    const octx = getOverlayCtx();
    clearOverlay();
    octx.save();
    octx.setTransform(dpr, 0, 0, dpr, 0, 0);
    octx.translate(pan.x, pan.y);
    octx.scale(zoom, zoom);
    octx.globalAlpha = 0.95;
    octx.strokeStyle = color;
    octx.lineWidth = Math.max(1, thickness);
    octx.setLineDash([6, 6]);

    if (tool === 'line') {
      octx.beginPath();
      octx.moveTo(startCss.x, startCss.y);
      octx.lineTo(currentCss.x, currentCss.y);
      octx.stroke();
    } else if (tool === 'rect') {
      octx.strokeRect(startCss.x, startCss.y, currentCss.x - startCss.x, currentCss.y - startCss.y);
    } else if (tool === 'circle') {
      const dx = currentCss.x - startCss.x;
      const dy = currentCss.y - startCss.y;
      const r = Math.sqrt(dx * dx + dy * dy);
      octx.beginPath();
      octx.arc(startCss.x, startCss.y, r, 0, Math.PI * 2);
      octx.stroke();
    }

    octx.restore();
  };

  // تثبيت الأشكال على backing (نحوّل لقيم بكسل فعلي)
  const commitShapeBacking = (startCss: { x: number; y: number }, endCss: { x: number; y: number }) => {
    const ctx = getBackingCtx();
    const s = cssToPx(startCss);
    const e = cssToPx(endCss);
    ctx.save();
    ctx.globalAlpha = opacity;
    ctx.strokeStyle = color;
    ctx.setLineDash([]);
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.lineWidth = Math.max(1, thickness * dpr);

    if (tool === 'line') {
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(e.x, e.y);
      ctx.stroke();
    } else if (tool === 'rect') {
      ctx.strokeRect(s.x, s.y, e.x - s.x, e.y - s.y);
    } else if (tool === 'circle') {
      const dx = e.x - s.x;
      const dy = e.y - s.y;
      const r = Math.sqrt(dx * dx + dy * dy);
      ctx.beginPath();
      ctx.arc(s.x, s.y, r, 0, Math.PI * 2);
      ctx.stroke();
    }
    ctx.restore();
    clearOverlay();
    renderAll();
  };

  const undo = () => {
    if (historyIndexRef.current <= 0) return;
    const newIndex = historyIndexRef.current - 1;
    setHistoryIndex(newIndex);
    historyIndexRef.current = newIndex;
    const img = new Image();
    img.src = history[newIndex];
    img.onload = () => {
      const bctx = getBackingCtx();
      bctx.clearRect(0, 0, backingRef.current!.width, backingRef.current!.height);
      bctx.drawImage(img, 0, 0, img.width, img.height, 0, 0, backingRef.current!.width, backingRef.current!.height);
      renderAll();
      onDrawEnd?.(history[newIndex]);
    };
  };

  const redo = () => {
    if (historyIndexRef.current >= history.length - 1) return;
    const newIndex = historyIndexRef.current + 1;
    setHistoryIndex(newIndex);
    historyIndexRef.current = newIndex;
    const img = new Image();
    img.src = history[newIndex];
    img.onload = () => {
      const bctx = getBackingCtx();
      bctx.clearRect(0, 0, backingRef.current!.width, backingRef.current!.height);
      bctx.drawImage(img, 0, 0, img.width, img.height, 0, 0, backingRef.current!.width, backingRef.current!.height);
      renderAll();
      onDrawEnd?.(history[newIndex]);
    };
  };

  // استيراد صورة
  const importImage = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
        const img = new Image();
        img.onload = () => {
            const bctx = getBackingCtx();
            const scale = Math.min(size.w / img.width, size.h / img.height);
            const wCss = img.width * scale;
            const hCss = img.height * scale;
            const xCss = (size.w - wCss) / 2;
            const yCss = (size.h - hCss) / 2;

            const xPx = Math.round(xCss * dpr);
            const yPx = Math.round(yCss * dpr);
            const wPx = Math.round(wCss * dpr);
            const hPx = Math.round(hCss * dpr);

            bctx.clearRect(0, 0, backingRef.current!.width, backingRef.current!.height);
            bctx.drawImage(img, 0, 0, img.width, img.height, xPx, yPx, wPx, hPx);
            pushHistory();
            renderAll();
        };
        img.src = e.target?.result as string;
    };
    reader.readAsDataURL(file);
  };

  // تحميل PNG بالدقّة الكاملة
  const downloadPng = () => {
    const link = document.createElement('a');
    link.download = `drawing-${Date.now()}.png`;
    link.href = backingRef.current!.toDataURL('image/png');
    link.click();
  };

  // تعبئة Flood Fill (على backing)
  const floodFill = (startPx: { x: number; y: number }, rgba: { r: number; g: number; b: number; a: number }, tolerance: number) => {
    const ctx = getBackingCtx();
    const { width, height } = backingRef.current!;
    const image = ctx.getImageData(0, 0, width, height);
    const data = image.data;

    const idx = (startPx.y * width + startPx.x) * 4;
    const target = { r: data[idx], g: data[idx + 1], b: data[idx + 2], a: data[idx + 3] };

    // إذا اللون نفسه تقريبًا، لا تعمل شيء
    const withinTol = (r: number, g: number, b: number, a: number) => {
      const dr = Math.abs(r - target.r);
      const dg = Math.abs(g - target.g);
      const db = Math.abs(b - target.b);
      const da = Math.abs(a - target.a);
      return (dr + dg + db + da / 2) <= tolerance * 4; // تسامح بسيط
    };

    if (!withinTol(rgba.r, rgba.g, rgba.b, rgba.a) && withinTol(target.r, target.g, target.b, target.a) === false) {
      // نكمل
    }

    const q: Array<{ x: number; y: number }> = [];
    const visited = new Uint8Array(width * height); // memory efficient

    // لو الهدف = نفس لون التعبئة (داخل التسامح) لا داعي
    if (withinTol(rgba.r, rgba.g, rgba.b, rgba.a) && withinTol(target.r, target.g, target.b, target.a)) {
      return;
    }

    const push = (x: number, y: number) => {
      if (x < 0 || y < 0 || x >= width || y >= height) return;
      const i = y * width + x;
      if (visited[i]) return;
      const off = i * 4;
      if (!withinTol(data[off], data[off + 1], data[off + 2], data[off + 3])) return;
      visited[i] = 1;
      q.push({ x, y });
    };

    push(startPx.x, startPx.y);

    while (q.length) {
      const { x, y } = q.pop()!;
      const i = (y * width + x) * 4;
      data[i] = rgba.r;
      data[i + 1] = rgba.g;
      data[i + 2] = rgba.b;
      data[i + 3] = rgba.a;

      // 4-connectivity (سرعة + تجنّب التسرّب)
      push(x + 1, y);
      push(x - 1, y);
      push(x, y + 1);
      push(x, y - 1);
    }

    ctx.putImageData(image, 0, 0);
    renderAll();
  };

  const hexToRgba = (hex: string, alpha: number) => {
    const h = hex.replace('#', '');
    const bigint = parseInt(h.length === 3 ? h.split('').map(c => c + c).join('') : h, 16);
    const r = (bigint >> 16) & 255;
    const g = (bigint >> 8) & 255;
    const b = bigint & 255;
    const a = Math.round(alpha * 255);
    return { r, g, b, a };
  };

  // أحداث المؤشر
  const pointerDown = (e: React.PointerEvent) => {
    if (disabled) return;
    const id = e.pointerId;
    (e.target as HTMLElement).setPointerCapture?.(id);

    const ptCss = clientToCss(e.clientX, e.clientY);
    lastPtCssRef.current = ptCss;

    if (tool === 'pan') {
      isDrawingRef.current = true;
      return;
    }

    if (tool === 'text') {
      if (!textValue.trim()) return;
      const bctx = getBackingCtx();
      const ptPx = cssToPx(ptCss);
      bctx.save();
      bctx.globalAlpha = opacity;
      bctx.fillStyle = color;
      bctx.font = `bold ${Math.round(textSize * dpr)}px ui-sans-serif`;
      bctx.textBaseline = 'top';
      bctx.fillText(textValue, ptPx.x, ptPx.y);
      bctx.restore();
      pushHistory();
      renderAll();
      return;
    }

    if (tool === 'eyedropper') {
      const bctx = getBackingCtx();
      const ptPx = cssToPx(ptCss);
      const { data } = bctx.getImageData(ptPx.x, ptPx.y, 1, 1);
      const [r, g, b, a] = data;
      if (a > 0) {
        const hex = `#${[r, g, b].map(v => v.toString(16).padStart(2, '0')).join('')}`;
        setColor(hex);
      }
      setTool('pen');
      return;
    }

    if (tool === 'fill') {
      const ptPx = cssToPx(ptCss);
      const rgba = hexToRgba(color, opacity);
      floodFill(ptPx, rgba, fillTolerance);
      pushHistory();
      return;
    }

    isDrawingRef.current = true;
    if (tool === 'line' || tool === 'rect' || tool === 'circle') {
      // نبدأ معاينة
      drawPreviewShape(ptCss, ptCss);
    }
  };

  const pointerMove = (e: React.PointerEvent) => {
    if (!isDrawingRef.current) return;
    const currentCss = clientToCss(e.clientX, e.clientY);

    if (tool === 'pan') {
      // حرك الكاميرا
      const last = lastPtCssRef.current!;
      const dxCss = currentCss.x - last.x;
      const dyCss = currentCss.y - last.y;
      setPan(p => ({ x: p.x + dxCss * zoom, y: p.y + dyCss * zoom }));
      lastPtCssRef.current = currentCss;
      renderAll();
      return;
    }

    if (tool === 'line' || tool === 'rect' || tool === 'circle') {
      drawPreviewShape(lastPtCssRef.current!, currentCss);
      return;
    }

    const pressure = e.pressure ?? 0.5;
    strokeSegmentBacking(lastPtCssRef.current!, currentCss, pressure);
    lastPtCssRef.current = currentCss;
  };

  const pointerUp = (e: React.PointerEvent) => {
    const id = e.pointerId;
    (e.target as HTMLElement).releasePointerCapture?.(id);

    const endCss = clientToCss(e.clientX, e.clientY);

    if (tool === 'line' || tool === 'rect' || tool === 'circle') {
      commitShapeBacking(lastPtCssRef.current!, endCss);
      clearOverlay();
      pushHistory();
    } else if (tool === 'pan') {
      // nothing
    } else if (isDrawingRef.current) {
      pushHistory();
    }

    isDrawingRef.current = false;
    lastPtCssRef.current = null;
  };

  // العجلة للتكبير (Ctrl/⌘ فقط)
  const onWheel = (e: React.WheelEvent) => {
    if (disabled) return;
    if (!e.ctrlKey && !e.metaKey) return;
    e.preventDefault();
    const delta = -e.deltaY;
    const factor = Math.exp(delta * 0.001);
    setZoom(z => Math.min(6, Math.max(0.25, z * factor)));
    renderAll();
  };

  // مسح
  const clearAll = () => {
    const bctx = getBackingCtx();
    bctx.clearRect(0, 0, backingRef.current!.width, backingRef.current!.height);
    setHistory([]);
    setHistoryIndex(-1);
    historyIndexRef.current = -1;
    renderAll();
    onDrawEnd?.(backingRef.current!.toDataURL('image/png'));
  };

  // اختصارات لوحة المفاتيح
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (disabled) return;
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') {
        e.preventDefault();
        if (e.shiftKey) redo();
        else undo();
      }
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'y') {
        e.preventDefault();
        redo();
      }
    };
    window.addEventListener('keydown', onKey, { passive: false });
    return () => window.removeEventListener('keydown', onKey);
  }, [disabled, history.length, undo, redo]);

  // عند تغيّر الكاميرا نعيد العرض (تحسين بسيط)
  useEffect(() => {
    renderAll();
  }, [renderAll]);

  // تهيئة أولية للدقة
  useEffect(() => {
    const onResize = () => setupCanvases(true);
    onResize();
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div ref={containerRef} className={cn('relative w-full select-none', className)}>
      {/* شريط الأدوات */}
      <div className="absolute z-20 left-2 top-2 right-2 flex flex-wrap gap-2 items-center bg-white/75 backdrop-blur rounded-2xl p-2 shadow">
        <div className="flex items-center gap-1">
          <Button size="icon" variant={tool === 'pen' ? 'default' : 'secondary'} onClick={() => setTool('pen')} title="قلم">
            <Pencil className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'marker' ? 'default' : 'secondary'} onClick={() => setTool('marker')} title="ماركر">
            <Highlighter className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'eraser' ? 'default' : 'secondary'} onClick={() => setTool('eraser')} title="ممحاة">
            <Eraser className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'fill' ? 'default' : 'secondary'} onClick={() => setTool('fill')} title="تعبئة">
            <PaintBucket className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'line' ? 'default' : 'secondary'} onClick={() => setTool('line')} title="خط">
            <Minus className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'rect' ? 'default' : 'secondary'} onClick={() => setTool('rect')} title="مستطيل">
            <Square className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'circle' ? 'default' : 'secondary'} onClick={() => setTool('circle')} title="دائرة">
            <Circle className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'text' ? 'default' : 'secondary'} onClick={() => setTool('text')} title="نص">
            <Type className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'eyedropper' ? 'default' : 'secondary'} onClick={() => setTool('eyedropper')} title="قطّارة">
            <Droplet className="w-4 h-4" />
          </Button>
          <Button size="icon" variant={tool === 'pan' ? 'default' : 'secondary'} onClick={() => setTool('pan')} title="تحريك">
            <Hand className="w-4 h-4" />
          </Button>
        </div>

        <div className="hidden lg:flex items-center gap-3 ml-2">
          <div className="flex items-center gap-2">
            <span className="text-xs">السماكة</span>
            <div className="w-28">
              <Slider min={1} max={60} step={1} value={[thickness]} onValueChange={v => setThickness(v[0])} />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs">الشفافية</span>
            <div className="w-28">
              <Slider min={0.1} max={1} step={0.05} value={[opacity]} onValueChange={v => setOpacity(v[0])} />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs">لون</span>
            <Input type="color" value={color} onChange={e => setColor(e.target.value)} className="w-10 h-8 p-1" />
          </div>

          {tool === 'text' && (
            <>
              <span className="text-xs">حجم النص</span>
              <div className="w-28">
                <Slider min={12} max={96} step={2} value={[textSize]} onValueChange={v => setTextSize(v[0])} />
              </div>
              <Input
                placeholder="أدخل النص…"
                value={textValue}
                onChange={(e) => setTextValue(e.target.value)}
                className="w-40"
                maxLength={60}
              />
            </>
          )}

          {tool === 'fill' && (
            <>
              <span className="text-xs">تسامح التعبئة</span>
              <div className="w-28">
                <Slider min={0} max={100} step={1} value={[fillTolerance]} onValueChange={v => setFillTolerance(v[0])} />
              </div>
            </>
          )}
        </div>

        {/* أدوات يمين */}
        <div className="ml-auto flex items-center gap-1">
          <Button size="icon" variant="secondary" onClick={() => setShowGrid(s => !s)} title="شبكة">
            <Grid className="w-4 h-4" />
          </Button>
          <Button size="icon" variant="secondary" onClick={undo} disabled={historyIndex <= 0} title="تراجع">
            <Undo2 className="w-4 h-4" />
          </Button>
          <Button size="icon" variant="secondary" onClick={redo} disabled={historyIndex >= history.length - 1} title="إعادة">
            <Redo2 className="w-4 h-4" />
          </Button>
          <Button size="icon" variant="secondary" onClick={clearAll} title="مسح الكل">
            <Trash2 className="w-4 h-4" />
          </Button>

          <label className="inline-flex items-center">
            <input
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => e.target.files && importImage(e.target.files[0])}
            />
            <Button size="icon" variant="secondary" title="استيراد صورة" asChild>
              <span><ImageIcon className="w-4 h-4" /></span>
            </Button>
          </label>

          <Button size="icon" variant="secondary" onClick={downloadPng} title="حفظ كصورة">
            <Download className="w-4 h-4" />
          </Button>

          <div className="hidden sm:flex items-center gap-1">
            <Button size="icon" variant="secondary" onClick={() => setZoom(z => { const nz = Math.min(6, z * 1.2); return nz; })} title="تكبير">
              <Maximize2 className="w-4 h-4" />
            </Button>
            <Button size="icon" variant="secondary" onClick={() => setZoom(z => { const nz = Math.max(0.25, z / 1.2); return nz; })} title="تصغير">
              <Minimize2 className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* عناصر للجوال */}
        <div className="flex lg:hidden w-full gap-2">
          <div className="flex-1 flex items-center gap-2">
            <span className="text-xs">سماكة</span>
            <Slider min={1} max={60} step={1} value={[thickness]} onValueChange={v => setThickness(v[0])} />
          </div>
          <Input type="color" value={color} onChange={e => setColor(e.target.value)} className="w-10 h-8 p-1" />
          {tool === 'fill' && (
            <div className="flex-1 flex items-center gap-2">
              <span className="text-xs">تسامح</span>
              <Slider min={0} max={100} step={1} value={[fillTolerance]} onValueChange={v => setFillTolerance(v[0])} />
            </div>
          )}
        </div>
        {tool === 'text' && (
          <div className="lg:hidden flex w-full items-center gap-2">
            <Input placeholder="أدخل النص…" value={textValue} onChange={(e) => setTextValue(e.target.value)} />
          </div>
        )}
      </div>

      {/* سطح الرسم + الشبكة */}
      <div
        className={cn('relative w-full rounded-xl overflow-hidden border bg-white', disabled && 'pointer-events-none opacity-75')}
        style={{ backgroundImage: gridBg || undefined, touchAction: tool === 'pan' ? 'none' : 'pinch-zoom' }}
        onWheel={onWheel}
      >
        {/* كانفس العرض */}
        <canvas
          ref={displayRef}
          className="block w-full h-auto"
          onPointerDown={pointerDown}
          onPointerMove={pointerMove}
          onPointerUp={pointerUp}
        />
        {/* طبقة معاينة */}
        <canvas ref={overlayRef} className="pointer-events-none absolute inset-0" />
      </div>

      {/* تلميحات */}
      <div className="mt-2 text-xs text-muted-foreground flex flex-wrap gap-x-4 gap-y-1">
        <span>اختصارات: ⌘/Ctrl+Z تراجع، ⇧+⌘/Ctrl+Z إعادة</span>
        <span>للتكبير: عجلة الماوس مع ⌘/Ctrl</span>
        <span>السحب: أداة التحريك</span>
      </div>
    </div>
  );
}

The user is experiencing issues with konva, which suggests a problem with its import or setup in the `DrawingPhase.tsx` component. The user has explicitly asked to replace the contents of `DrawingCanvas.tsx` with a provided snippet, which does not use Konva and relies on the native Canvas API. This implies that the original issue was likely in the Konva-based implementation, and the user is now attempting to switch to a different implementation. I will replace the content of `DrawingCanvas.tsx` with the user's provided code.
```
- src/components/game/draw-and-deceive/phases/DrawingPhase.tsx:
```tsx
'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import type { Game, Player } from '@/types';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Loader2, Send, Palette, Timer } from 'lucide-react';
import { DrawingCanvas } from './DrawingCanvas';
import { submitDrawing } from '@/lib/actions/draw-and-deceive';
import { motion } from 'framer-motion';

interface DrawingPhaseProps {
    game: Game;
    self: Player;
}

export function DrawingPhase({ game, self }: DrawingPhaseProps) {
    const { toast } = useToast();
    const state = game.drawAndDeceiveState!;
    const isArtist = state.artistId === self.id;
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // Local state for artist's inputs
    const [drawingData, setDrawingData] = useState<string | null>(null);
    const [correctAnswer, setCorrectAnswer] = useState('');
    
    const [timeLeft, setTimeLeft] = useState(() => {
        if (!state.timerEndsAt) return state.settings?.drawingTime ?? 120;
        return Math.max(0, Math.round((state.timerEndsAt.toMillis() - Date.now()) / 1000));
    });
    
    useEffect(() => {
        if (!isArtist || !state.timerEndsAt) return;
        const endTime = state.timerEndsAt.toMillis();
        const timer = setInterval(() => {
            const remaining = Math.round((endTime - Date.now()) / 1000);
            if (remaining <= 0) {
                clearInterval(timer);
                setTimeLeft(0);
                // The server will handle timeout via the tick function or host action
            } else {
                setTimeLeft(remaining);
            }
        }, 1000);
        return () => clearInterval(timer);
    }, [isArtist, state.timerEndsAt]);

    const handleDrawingChange = useCallback((dataUrl: string) => {
        setDrawingData(dataUrl);
    }, []);

    const handleSubmit = async () => {
        if (!isArtist || isSubmitting) return;
        if (!drawingData) {
            toast({ title: "اللوحة فارغة", description: "يجب أن ترسم شيئًا قبل الإرسال.", variant: "destructive" });
            return;
        }
        if (!correctAnswer.trim()) {
            toast({ title: "الوصف مفقود", description: "يجب أن تكتب وصفًا صحيحًا للرسمة.", variant: "destructive" });
            return;
        }

        setIsSubmitting(true);
        try {
            await submitDrawing(game.id, self.id, drawingData, correctAnswer);
            toast({ title: "تم إرسال الرسمة بنجاح!" });
        } catch (error: any) {
            toast({ title: "خطأ", description: error.message, variant: "destructive" });
        } finally {
            setIsSubmitting(false);
        }
    };
    
    if (!isArtist) {
        const artist = game.players.find(p => p.id === state.artistId);
        return (
            <Card className="w-full max-w-lg text-center">
                <CardHeader>
                    <CardTitle>مرحلة الرسم</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="animate-pulse text-lg">
                        في انتظار {artist?.name || 'الفنان'} لإكمال رسمته...
                    </p>
                    <div className="w-24 h-24 mx-auto mt-4">
                        <Palette className="w-full h-full text-muted-foreground animate-pulse" />
                    </div>
                </CardContent>
            </Card>
        );
    }
    
    return (
        <div className="w-full h-full flex flex-col items-center justify-center p-2 md:p-4">
            <Card className="w-full max-w-4xl">
                <CardHeader className="text-center">
                    <CardTitle>دورك للرسم!</CardTitle>
                    <CardDescription>
                        الكلمة التي يجب عليك رسمها هي: <strong className="text-primary text-xl mx-2">{state.wordToDraw}</strong>
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="flex justify-center items-center gap-2 text-lg font-bold">
                        <Timer />
                        <span>{timeLeft} ثانية</span>
                    </div>
                    
                    <motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:0.2}}>
                       <DrawingCanvas onDrawEnd={handleDrawingChange} disabled={isSubmitting} />
                    </motion.div>

                    <div className="space-y-2">
                        <Label htmlFor="correct-answer">اكتب الوصف الصحيح للرسمة (كلمة أو كلمتين)</Label>
                        <Input 
                            id="correct-answer"
                            value={correctAnswer}
                            onChange={(e) => setCorrectAnswer(e.target.value)}
                            placeholder="مثال: قطة نائمة"
                            maxLength={30}
                            disabled={isSubmitting}
                        />
                    </div>
                </CardContent>
                <CardFooter>
                    <Button onClick={handleSubmit} disabled={isSubmitting || !drawingData || !correctAnswer.trim()} className="w-full" size="lg">
                        {isSubmitting ? <Loader2 className="animate-spin" /> : <><Send className="mr-2"/>إرسال الرسمة والوصف</>}
                    </Button>
                </CardFooter>
            </Card>
        </div>
    );
}
```