"use client";

import type { Metadata, Viewport } from "next";

// =============================
// Metadata (SEO + Social Cards)
// =============================
export const metadata: Metadata = {
  title: {
    default: "سجل المباريات",
    template: "%s • سجل المباريات",
  },
  description: "اطلع على تاريخ مبارياتك ونتائجها.",
  applicationName: "PlayVerse",
  keywords: ["سجل", "مباريات", "ألعاب", "نتائج", "تاريخ"],
  authors: [{ name: "PlayVerse" }],
  icons: { icon: "/favicon.ico" },
  alternates: { canonical: "/history" },
  openGraph: {
    type: "website",
    locale: "ar_SA",
    title: "سجل المباريات",
    description: "اطلع على تاريخ مبارياتك ونتائجها.",
    url: "/history",
    siteName: "PlayVerse",
  },
  twitter: {
    card: "summary_large_image",
    title: "سجل المباريات",
    description: "اطلع على تاريخ مبارياتك ونتائجها.",
  },
  robots: {
    index: true,
    follow: true,
  },
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#6D28D9" }, // violet-700
    { media: "(prefers-color-scheme: dark)", color: "#A78BFA" }, // violet-300
  ],
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#6D28D9" },
    { media: "(prefers-color-scheme: dark)", color: "#A78BFA" },
  ],
};

// =============================
// Layout (RTL-friendly, Minimal)
// - متناسق مع صفحة سجل المباريات المحسّنة (بنفسجي/أبيض)
// - وصولية: رابط تخطّي للمحتوى + لغة واتجاه
// - بدون حشو بصري: تترك الخلفية للصفحة نفسها
// - Generated by GPT-5 Thinking
// =============================
export default function HistoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section dir="rtl" lang="ar" className="antialiased">
      {/* Skip to content for screen readers / keyboard users */}
      <a
        href="#history-content"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:right-2 focus:z-50 focus:rounded-lg focus:bg-white focus:px-3 focus:py-2 focus:text-violet-900 shadow-sm dark:focus:bg-gray-900 dark:focus:text-violet-100"
      >
        الانتقال إلى المحتوى
      </a>

      {/* Anchor target used by the page <main id=\"history-content\" /> */}
      {children}

      {/* Subtle global polish to match violet/white theme without being flashy */}
      <style jsx global>{`
        :root {
          --accent-violet: #6D28D9; /* violet-700 */
          --accent-violet-weak: #8B5CF6; /* violet-500 */
        }
        .focus-violet:focus-visible {
          outline: 2px solid var(--accent-violet);
          outline-offset: 2px;
        }
        /* Smooth scroll for dialog anchors and match deep-links */
        html { scroll-behavior: smooth; }
      `}</style>
    </section>
  );
}
